name: build and test

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download JDK'
        id: jdk
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 21

      - name: 'Check out repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: run tests
        shell: bash
        working-directory: .github/tools
        run: |
          mvn test -Dexecution.endpoint=https://i67ddx34g3dcytoxovnbl45u6m.apigateway.us-ashburn-1.oci.customer-oci.com/api/execute

